### ISSUE TITLE
automatic rounding

### ISSUE THREAD

**Issue by RuthFG** [ices-tools-prod/icesSAG#155] opened 2018-04-10 15:50 UTC
Hi, it seems that the rounding is not applied to the custom columns. See here cod.27.22-24 stock

![capture](https://user-images.githubusercontent.com/33519586/38567908-d5992474-3cd6-11e8-8eee-e7d737470dfb.PNG)

**Comment by colinpmillar** [comment] 2018-04-12 09:51
duplicate of:
Implement rounding rules #43

**Closed** 2018-04-12 09:52 UTC

**Comment by RuthFG** [comment] 2018-05-11 10:35
The non-rounding of custom columns is still a bit of an issue. We can of course round the values manually but if it can be easily fixed, this will make our life easier.

Three of my WGBFAS stocks have non rounded custom columns with quite a lot of values
https://standardgraphs.ices.dk/manage/ViewGraphsAndTables.aspx?key=9401
https://standardgraphs.ices.dk/manage/ViewGraphsAndTables.aspx?key=9479
https://standardgraphs.ices.dk/manage/ViewGraphsAndTables.aspx?key=9431
