### ISSUE TITLE
rounding fails (sometimes)

### ISSUE THREAD

**Issue by RuthFG** [ices-tools-prod/icesSAG#156] opened 2018-04-11 14:29 UTC
Hello,

For these 2 stocks, when we download the data as a .doc document we don’t get the right numbers . Can you check?

https://standardgraphs.ices.dk/manage/ViewGraphsAndTables.aspx?key=9428
https://standardgraphs.ices.dk/manage/ViewGraphsAndTables.aspx?key=9415

See attachment
[SAG rounding issue.docx](https://github.com/ices-tools-prod/icesSAG/files/1899234/SAG.rounding.issue.docx)

Ruth

**Comment by cmspinto** [comment] 2018-04-12 09:27
The rounding rule is in use in both (the download and the page in the same way).
@colinpmillar  can we link this with the rouding rules issue so we have only one issue on the rounding rules?

**Comment by colinpmillar** [comment] 2018-04-12 09:53
duplicate of:
Implement rounding rules #43

**Comment by colinpmillar** [comment] 2018-04-12 09:54
@cmspinto I have put these as comments in the original issue #43 so we have one issue to deal with :)

**Closed by colinpmillar** 2018-04-12 09:54 UTC

**Comment by RuthFG** [comment] 2018-05-23 09:37
This is still an issue for some stocks. For example this one
https://standardgraphs.ices.dk/manage/ViewGraphsAndTables.aspx?key=9425

All looks good online but when downloading the word file the numbers for landings/discards are less precise than the input data/what we see online
![capture](https://user-images.githubusercontent.com/33519586/40416456-d7397236-5e6c-11e8-968b-88e5a55ebf7a.PNG)
