### ISSUE TITLE
Create user manual for SAG

### ISSUE THREAD

**Issue by slarge** [ices-tools-prod/icesSAG#65] opened 2017-05-04 06:18 UTC
Currently, there are useful instructions, but they are not detailed enough to completely guide an expert through the process. Perhaps next time we have an intern they can go through and create text to embed throughout the UI and create a standalone document demonstrating how to use the program. Lots of time is spent re-instructing people how to change from landings to catches plots or how to adjust the scaling on the axes.

link to #41

**Comment by colinpmillar** [comment] 2017-05-04 08:21
duplicate of #41

**Closed** 2017-05-04 08:27 UTC
Labels: duplicate
